- block:
    - name: Checking denyhosts status
      service:
        name: denyhosts
        state: started
      changed_when: false
  rescue:
    - include_tasks: allowed_hosts.yml
    - name: Installing epel-release
      yum:
        name: epel-release
      when: ansible_os_family == 'RedHat'
    - name: Installing denyhosts
      package:
        name: denyhosts
      notify: Restart denyhosts

- include_tasks: allowed_hosts.yml

- name: Updating /etc/denyhosts.conf
  template:
    src: denyhosts.conf.j2
    dest: /etc/denyhosts.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart denyhosts
